import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import assert from 'node:assert/strict';

const root = new URL('../', import.meta.url);

async function file(path) {
  return readFile(new URL(path, root), 'utf8');
}

test('home page renders a centered writing draft', async () => {
  const html = await file('index.html');
  const css = await file('styles.css');
  const app = await file('src/app.js');

  assert.match(html, /id="article-root"/);
  assert.doesNotMatch(html, /data-admin/);
  assert.doesNotMatch(html, /generate-en|hyun2\.llmConfig|LLM_GATEWAY_API_KEY/);
  assert.match(html, /src="\.\/src\/app\.js\?v=/);
  assert.match(css, /--bg:\s*#fff/);
  assert.match(css, /--fg:\s*#000/);
  assert.match(html, /Gowun\+Batang/);
  assert.match(html, /Noto\+Serif\+KR/);
  assert.doesNotMatch(app, /title:\s*'가안: 가운데에 놓인 글'/);
  assert.match(app, /centered-draft/);
  assert.match(app, /renderArticle/);
  assert.match(app, /article__date/);
  assert.match(app, /formatDate/);
  assert.doesNotMatch(app, /article__meta/);
  assert.doesNotMatch(app, /renderArticle\(local\)/);
  assert.match(app, /isBootstrapArticle/);
  assert.match(app, /filterBootstrapPosts/);
  assert.match(app, /blankArticle/);
});

test('Supabase client is wired to the target project without secret keys', async () => {
  const config = await file('src/supabase-config.js');
  const client = await file('src/supabase-client.js');

  assert.match(config, /ltmkpotvrxgoyyuzfvlv\.supabase\.co/);
  assert.doesNotMatch(config, /service_role|sb_secret_/i);
  assert.match(client, /\/rest\/v1\/posts/);
  assert.match(client, /status=eq\.published/);
  assert.match(client, /listPostTitles/);
  assert.match(client, /getPostBySlug/);
  assert.match(client, /TITLE_SELECT = 'id,title,slug,status,published_at,updated_at,content'/);
  assert.match(client, /status', 'neq\.archived'/);
});

test('admin page can sign in, list titles, set pt sizes, and save writing', async () => {
  const adminHtml = await file('admin.html');
  const app = await file('src/app.js');
  const client = await file('src/supabase-client.js');
  const css = await file('styles.css');

  assert.match(adminHtml, /data-admin="true"/);
  assert.match(adminHtml, /src="\.\/src\/app\.js\?v=/);
  assert.match(app, /isAdminPage/);
  assert.match(app, /supabase-client\.js\?v=/);
  assert.match(app, /data-panel="index"/);
  assert.match(app, /reader-layout[\s\S]*renderReaderIndex\(posts, view\.slug\)[\s\S]*renderTopControls\('reader-chrome'\)/);
  assert.match(app, /name="titleSizePt"/);
  assert.match(app, /name="bodySizePt"/);
  assert.match(app, /name="bodyLineHeight"/);
  assert.match(app, /name="indentPt"/);
  assert.match(app, /bodyLineHeight/);
  assert.match(app, /indentPt/);
  assert.match(app, /pt/);
  assert.match(app, /contenteditable="true"/);
  assert.match(app, /insertImageFiles/);
  assert.match(app, /imageUploadFailureMessage/);
  assert.match(app, /storage bucket missing/);
  assert.match(app, /supabase\/schema\.sql/);
  assert.match(app, /data-block-type="image"/);
  assert.match(app, /uploadPostImage/);
  assert.match(app, /optimizedImageFile/);
  assert.match(app, /hasImageInDataTransfer/);
  assert.match(app, /dataTransfer\?\.items/);
  assert.match(app, /item\.kind === 'file'/);
  assert.match(app, /data-image-action="wrap"/);
  assert.match(app, /enableImageTextWrap/);
  assert.match(app, /figure\.dataset\.width = '42'/);
  assert.match(app, /figure\.dataset\.align = 'left'/);
  assert.match(app, /data-panel="image"/);
  assert.match(app, /editor-side-panel/);
  assert.match(app, /data-panel="side"/);
  assert.match(app, /<aside class="editor-side-panel"[\s\S]*<p class="editor__status"/);
  assert.match(app, /data-action="align-left"/);
  assert.match(app, /data-action="align-center"/);
  assert.match(app, /data-action="align-right"/);
  assert.match(app, /data-action="indent-none"/);
  assert.match(app, /alignSelectedBlocks/);
  assert.match(app, /removeIndentFromSelectedBlocks/);
  assert.match(app, /applySelectedBlockStyle/);
  assert.match(app, /clearSelectedBlockStyle/);
  assert.match(app, /selectedCaptionFigure/);
  assert.match(app, /selectedCaptionFigure && !selectionCoversContentRoot/);
  assert.match(app, /image caption style changed/);
  assert.match(app, /return;\s*\n\s*}/);
  assert.match(app, /name="paragraphFont"/);
  assert.match(app, /name="paragraphWeight"/);
  assert.match(app, /name="paragraphSizePt"/);
  assert.match(app, /name="paragraphLetterSpacing"/);
  assert.match(app, /name="paragraphIndentPt"/);
  assert.match(app, /normalizeLetterSpacing/);
  assert.match(app, /normalizeParagraphIndentPt/);
  assert.match(app, /letterSpacing/);
  assert.match(app, /indentPt/);
  assert.match(app, /PARAGRAPH_STYLE_PRESETS_KEY/);
  assert.match(app, /hyun2\.paragraphStylePresets/);
  assert.match(app, /name="paragraphStylePreset"/);
  assert.match(app, /name="paragraphStylePresetName"/);
  assert.match(app, /data-action="paragraph-style-save"/);
  assert.match(app, /data-action="paragraph-style-load"/);
  assert.match(app, /saveParagraphStylePreset/);
  assert.match(app, /applyParagraphStylePreset/);
  assert.match(app, /defaultParagraphStyleControls/);
  assert.match(app, /paragraphStyleControlsWithDefaults/);
  assert.match(app, /applyParagraphStyleControlsImmediately/);
  assert.match(app, /paragraphControlFields/);
  assert.match(app, /applyParagraphStylePreset\(root, statusRoot, \{ contentRoot, history \}\)/);
  assert.match(app, /PARAGRAPH_FONT_OPTIONS/);
  assert.match(app, /paragraphFontOptionsMarkup/);
  assert.match(app, /paragraphWeightsForFont/);
  assert.match(app, /renderParagraphWeightOptions/);
  assert.match(app, /syncParagraphWeightOptions/);
  assert.match(app, /normalizeParagraphWeight\(.*font/);
  assert.match(app, /selectionCoversContentRoot/);
  assert.match(app, /let lastEditorBlockRange/);
  assert.match(app, /rangeTouchesContent/);
  assert.match(app, /selectionRangeTouchingContent/);
  assert.match(app, /selectionRangeForBlocks/);
  assert.match(app, /fallbackEditorBlockRange/);
  assert.match(app, /selectedImageFiguresForStyle/);
  assert.match(app, /applyImageCaptionTypography/);
  assert.match(app, /data-caption-font/);
  assert.match(app, /data-caption-font-weight/);
  assert.match(app, /captionFont/);
  assert.match(app, /captionFontWeight/);
  assert.match(app, /data-action="paragraph-style"/);
  assert.match(app, /data-action="paragraph-style-clear"/);
  assert.match(app, /selectedEditableBlocks/);
  assert.match(app, /writeParagraphStyleControls\(root, defaultParagraphStyleControls\(\)\)/);
  assert.match(app, /image-resize-handle/);
  assert.match(app, /attachImageResizeDrag/);
  assert.match(app, /attachImageMove/);
  assert.match(app, /attachImagePointerMove/);
  assert.match(app, /pointerdown/);
  assert.match(app, /pointermove/);
  assert.match(app, /pointerup/);
  assert.match(app, /setPointerCapture/);
  assert.match(app, /image moved\. save to publish/);
  assert.match(app, /insertImageAtDropPoint/);
  assert.match(app, /insertImageAtParagraphBoundary/);
  assert.doesNotMatch(app, /splitParagraphForImage/);
  assert.match(app, /image-drop-indicator/);
  assert.match(app, /clearSelectedImageFigure/);
  assert.match(app, /moveExistingImageBlock/);
  assert.match(app, /HYUN2_IMAGE_MOVE_TYPE/);
  assert.match(app, /dataTransferHasType/);
  assert.match(app, /text\/plain/);
  assert.match(app, /figure\.draggable = false/);
  assert.match(app, /image\.draggable = false/);
  assert.match(app, /selectImageFigure/);
  assert.match(app, /syncImagePanel/);
  assert.match(app, /isEditorSidePanelClick/);
  assert.match(app, /closest\?\.\('\[data-panel="side"\]'\)/);
  assert.match(app, /name="imageWidth"/);
  assert.match(app, /name="imageHeight"/);
  assert.match(app, /name="imageMarginTop"/);
  assert.match(app, /name="imageMarginRight"/);
  assert.match(app, /name="imageMarginBottom"/);
  assert.match(app, /name="imageMarginLeft"/);
  assert.match(app, /min="-240"/);
  assert.match(app, /normalizeImageMarginPt\(value, fallback = DEFAULT_IMAGE_MARGIN_PT\)[\s\S]*Math\.max\(-240/);
  assert.match(app, /name="imageCaption"/);
  assert.match(app, /<textarea name="imageCaption"/);
  assert.doesNotMatch(app, /<input name="imageCaption"/);
  assert.match(app, /data-image-action="delete"/);
  assert.match(app, /deleteSelectedImageFigure/);
  assert.match(app, /image deleted\. save to publish/);
  assert.match(app, /data-caption/);
  assert.match(app, /figcaption/);
  assert.match(app, />왼쪽</);
  assert.match(app, />가운데</);
  assert.match(app, />오른쪽</);
  assert.match(app, /image layout changed/);
  assert.match(app, /data-action="save"/);
  assert.match(app, /data-action="generate-en"/);
  assert.match(app, /LLM_CONFIG_KEY/);
  assert.match(app, /hyun2\.llmConfig/);
  assert.match(app, /loadLlmConfig/);
  assert.match(app, /saveLlmConfig/);
  assert.match(app, /promptForLlmConfig/);
  assert.match(app, /LLM_REQUEST_TIMEOUT_MS/);
  assert.match(app, /AbortController/);
  assert.match(app, /llm-timeout/);
  assert.match(app, /llm-network/);
  assert.match(app, /setLlmProgress/);
  assert.match(app, /data-panel="llm-progress"/);
  assert.match(app, /35,\s*'생성'/);
  assert.match(app, /requestHyun2EnglishSuggestion/);
  assert.match(app, /strictHyun2LlmPrompt/);
  assert.match(app, /validateHyun2EnglishSuggestion/);
  assert.match(app, /applyHyun2EnglishSuggestion/);
  assert.match(app, /buildHyun2LlmPayload/);
  assert.match(app, /extractHyun2NotesFromHtml/);
  assert.match(app, /insertGeneratedNoteDot/);
  assert.match(app, /generateEnglishVersion/);
  assert.match(app, /titleEn/);
  assert.match(app, /htmlEn/);
  assert.match(app, /captionEn/);
  assert.match(app, /setEditorLang\('en'\)/);
  assert.match(app, /llmProgressText:\s*'100% 완료'/);
  assert.match(app, /English generated/);
  assert.doesNotMatch(app, /6a643474c193fabad3212dcaa191ed7c8065faa16aba828cd4395d16fd25af75/);
  assert.doesNotMatch(adminHtml, /100\.91\.137\.6:8787/);
  assert.doesNotMatch(adminHtml, /LLM_GATEWAY_API_KEY/);
  assert.match(app, /data-action="theme"/);
  assert.match(app, /savePostWithSession/);
  assert.match(app, /refreshSessionIfNeeded/);
  assert.match(app, /data-action="publish"/);
  assert.match(app, /status: published/);
  assert.match(app, /createEditorHistory/);
  assert.match(app, /snapshotEditorState/);
  assert.match(app, /restoreEditorState/);
  assert.match(app, /history\.commit/);
  assert.match(app, /event\.metaKey \|\| event\.ctrlKey/);
  assert.match(app, /attachEditorSaveShortcut/);
  assert.match(app, /event\.key\.toLowerCase\(\) === 's'/);
  assert.match(app, /event\.preventDefault\(\)/);
  assert.match(app, /selected paragraph style changed/);
  assert.match(app, /status: draft/);
  assert.match(app, /status = publishEnabled\(\) \? 'published' : 'draft'/);
  assert.match(app, /name="displayDate"/);
  assert.match(app, /dateInputToIso/);
  assert.match(app, /displayDate/);
  assert.match(app, /saved to Supabase as draft/);
  assert.match(app, /data-action="trash"/);
  assert.match(app, /status:\s*'archived'/);
  assert.match(app, /trash/);
  assert.match(app, /draggable="false"/);
  assert.match(app, /renderGroup\('published', 'published'/);
  assert.match(app, /renderGroup\('draft', 'draft'/);
  assert.match(app, /data-index-group="\$\{group\}"/);
  assert.match(app, /updatePostContent/);
  assert.match(app, /menu order saved/);
  assert.match(app, /querySelectorAll\('\.admin-index__items'\)/);
  assert.match(app, /adminDropTargetAfter/);
  assert.match(app, /persistAdminIndexOrder/);
  assert.match(app, /localStorage/);
  assert.match(client, /\/auth\/v1\/token\?grant_type=password/);
  assert.match(client, /savePost/);
  assert.match(client, /uploadPostImage/);
  assert.match(client, /\/storage\/v1\/object\/\$\{STORAGE_BUCKET\}/);
  assert.match(client, /upsert/);
  assert.match(client, /no-returned-row/);
  assert.match(client, /saved-as-new-row/);
  assert.match(client, /cloneLockedPost/);
  assert.match(app, /reader is updated/);
  assert.match(app, /dedupePostTitles/);
  assert.match(css, /--body-line-height/);
  assert.match(css, /\.article__body\s*\{[^}]*font-family:\s*var\(--font-gowun-batang\)/);
  assert.match(css, /\.article__body p \+ p[\s\S]*margin-top:\s*0/);
  assert.match(css, /--paragraph-indent/);
  assert.match(app, /firstTextBlockSeen/);
  assert.match(app, /articleBlocksMarkup/);
  assert.match(app, /normalizeFirstTextBlockMarker/);
  assert.match(app, /attachFirstTextBlockGuard/);
  assert.match(app, /data-first-text-block="true"/);
  assert.match(css, /\.article__body p\[data-first-text-block="true"\][\s\S]*text-indent:\s*0/);
  assert.doesNotMatch(css, /\.article__body p:first-of-type[\s\S]*text-indent:\s*0/);
  assert.match(css, /\.article-image--wrap/);
  assert.match(css, /\.article-image--wrap[\s\S]*max-width:\s*64%/);
  assert.match(css, /\.article-image--wrap[\s\S]*shape-outside:\s*margin-box/);
  assert.match(css, /\.editor__progress/);
  assert.match(css, /\.editor__progress\.is-error/);
  assert.match(css, /--image-margin-top/);
  assert.match(css, /--image-margin-right/);
  assert.match(css, /--image-margin-bottom/);
  assert.match(css, /--image-margin-left/);
  assert.match(css, /--image-height/);
  assert.match(css, /\.article-image figcaption/);
  assert.match(css, /\.article-image figcaption[\s\S]*white-space:\s*pre-wrap/);
  assert.match(css, /\.article-image figcaption\[data-font="jibaek"\]/);
  assert.match(css, /\.article-image figcaption\[data-font-weight="260"\]/);
  assert.match(css, /float:\s*left/);
  assert.match(css, /float:\s*right/);
  assert.match(css, /\.image-panel/);
  assert.match(css, /\.editor-side-panel/);
  assert.match(css, /\.editor-side-panel[\s\S]*position:\s*fixed/);
  assert.match(css, /\.editor-side-panel[\s\S]*max-height:\s*calc\(100vh - 48px\)/);
  assert.match(css, /\.editor-side-panel[\s\S]*overflow-y:\s*auto/);
  assert.match(css, /\.editor-side-panel[\s\S]*overscroll-behavior:\s*contain/);
  assert.match(css, /input\[name="displayDate"\][\s\S]*width:\s*100%/);
  assert.match(css, /\.editor__inline-tools[\s\S]*display:\s*inline-flex/);
  assert.match(css, /\.editor-align-tools/);
  assert.match(css, /\.icon-tool/);
  assert.match(css, /\.tool-icon--link/);
  assert.match(css, /\.tool-icon--bold/);
  assert.match(css, /\.tool-icon--italic/);
  assert.match(css, /\.tool-icon--align-center/);
  assert.match(css, /@font-face[\s\S]*font-family:\s*"SM3 Gyeonchul Myeongjo"/);
  assert.match(css, /@font-face[\s\S]*font-family:\s*"SM3 Sinsin Myeongjo"/);
  assert.match(css, /@font-face[\s\S]*font-family:\s*"Times LT Std"/);
  assert.match(css, /@font-face[\s\S]*font-family:\s*"Jibaek"/);
  assert.match(css, /Jibaek-120g-beta\.otf[\s\S]*font-weight:\s*120/);
  assert.match(css, /Jibaek-260g-beta\.otf[\s\S]*font-weight:\s*260/);
  assert.match(css, /Jibaek-400g-beta\.otf[\s\S]*font-weight:\s*400/);
  assert.match(css, /--font-ag-choijeongho-screen/);
  assert.match(css, /--font-ag-choijeongho-screen:[^;]*Noto Serif KR[^;]*Gowun Batang/);
  assert.match(css, /--font-sm3-gyeonchul-myeongjo/);
  assert.match(css, /--font-sm3-sinsin-myeongjo/);
  assert.match(css, /--font-times-lt-std/);
  assert.match(css, /--font-jibaek/);
  assert.match(css, /--font-gowun-batang/);
  assert.match(css, /--font-apple-sd-gothic-neo/);
  assert.match(css, /--font-latin-mix/);
  assert.match(css, /\.article__body p\[data-font="ag-choijeongho-screen"\]/);
  assert.match(css, /\.article__body p\[data-font="sm3-gyeonchul-myeongjo"\]/);
  assert.match(css, /\.article__body p\[data-font="sm3-sinsin-myeongjo"\]/);
  assert.match(css, /\.article__body p\[data-font="times-lt-std"\]/);
  assert.match(css, /\.article__body p\[data-font="jibaek"\]/);
  assert.match(css, /\.article__body p\[data-font-weight="120"\]/);
  assert.match(css, /\.article__body p\[data-font-weight="260"\]/);
  assert.match(css, /\.article__body p\[data-font-weight="400"\]/);
  assert.match(css, /\.article__body p\[data-font="gowun-batang"\]/);
  assert.match(css, /\.article__body p\[data-font="apple-sd-gothic-neo"\]/);
  assert.match(css, /\.article__body p\[data-size-pt\]/);
  assert.match(css, /\.article__body p\[data-indent-pt\]/);
  assert.match(css, /\.article__body p\[data-letter-spacing\]/);
  assert.match(css, /\.article-image figcaption\[data-letter-spacing\]/);
  assert.match(css, /\.image-drop-indicator/);
  assert.match(css, /\.article__body p\[data-align="center"\]/);
  assert.match(css, /\.article__body p\[data-indent="none"\]/);
  assert.match(css, /\.article-image img[\s\S]*cursor:\s*grab/);
  assert.match(css, /--image-gap:\s*0\.55em/);
  assert.match(css, /\.article__body p \+ \.article-image[\s\S]*margin-top:\s*var\(--image-margin-top\)/);
  assert.match(css, /\.article__body p \+ \.article-image--wrap[\s\S]*margin-top:\s*var\(--image-margin-top\)/);
  assert.match(css, /\.article-image \+ p[\s\S]*margin-top:\s*0/);
  assert.match(css, /\.article-image[\s\S]*margin-bottom:\s*var\(--image-margin-bottom\)/);
  assert.match(css, /\.article-image--wrap\[data-align="left"\][\s\S]*margin:\s*var\(--image-margin-top\) var\(--image-margin-right\) var\(--image-margin-bottom\) var\(--image-margin-left\)/);
  assert.match(css, /\.article-image--wrap\[data-align="right"\][\s\S]*margin:\s*var\(--image-margin-top\) var\(--image-margin-right\) var\(--image-margin-bottom\) var\(--image-margin-left\)/);
  assert.match(app, /AUTO_WRAP_IMAGE_WIDTH/);
  assert.match(app, /maybeAutoEnableImageWrap/);
  assert.match(css, /\.image-resize-handle/);
  assert.match(css, /\.article-image\.is-selected/);
  assert.match(css, /\.admin-layout[\s\S]*margin:\s*0 auto/);
  assert.match(css, /\.admin-index[\s\S]*position:\s*fixed/);
  assert.match(css, /hyphens:\s*auto/);
  assert.match(css, /data-theme="dark"/);
  assert.match(css, /#0645ff|#06f|blue/i);
  assert.match(css, /Gowun Batang/);
  assert.doesNotMatch(app, /--paragraph-gap/);
  assert.doesNotMatch(app, /supabase ready/);
});

test('reader and editor support index-only, mobile top, word wrapping, annotations, and underline marks', async () => {
  const app = await file('src/app.js');
  const css = await file('styles.css');

  assert.match(app, /routeParams\.has\('index'\)/);
  assert.match(app, /renderIndexPage/);
  assert.match(app, /href="\.\/\?index"/);
  assert.doesNotMatch(app, /<h1>index<\/h1>/);
  assert.match(app, /data-action="top"/);
  assert.match(app, /scrollTo\(\{\s*top:\s*0,\s*behavior:\s*'smooth'/);
  assert.match(app, /renderTopControls/);
  assert.match(app, /data-action="lang-toggle"/);
  assert.match(app, /data-action="editor-lang"/);
  assert.match(app, /currentEditorLang/);
  assert.match(app, /setEditorLang/);
  assert.match(app, /preserveEmptyEnglishTextBlock/);
  assert.match(app, /lang === 'en' && existing\.type === 'text'/);
  assert.match(app, /lang !== 'en' && existing\.htmlEn/);
  assert.match(app, /let blockIndex = 0/);
  assert.match(app, /existingBlocks\[blockIndex\]/);
  assert.match(app, /blockIndex \+= 1/);
  assert.match(app, /localizedArticleTitle/);
  assert.match(app, /localizedBlockHtml/);
  assert.match(app, /localizedImageCaption/);
  assert.match(app, /renderIndexPage\(window\.hyun2Posts \?\? \[\]\)/);
  assert.match(app, /localizedArticleTitle\(post, lang\)/);
  assert.match(app, /titleEn/);
  assert.match(app, /htmlEn/);
  assert.match(app, /captionEn/);
  assert.match(app, /data-caption-en/);
  assert.match(app, /data-lang="en"/);
  assert.match(app, /data-action="theme-toggle"/);
  assert.match(app, /toggleLang/);
  assert.match(app, /한/);
  assert.match(app, /EN/);
  assert.match(app, /themeLabel/);
  assert.match(app, /DA/);
  assert.match(app, /LA/);
  assert.match(app, /data-action="underline"/);
  assert.match(app, /data-action="bold"/);
  assert.match(app, /data-action="italic"/);
  assert.match(app, /normalizeParagraphWeight/);
  assert.match(app, /data-font-weight/);
  assert.match(app, /paragraphWeight/);
  assert.match(app, /SM3 Gyeonchul Myeongjo/);
  assert.match(app, /SM3 Sinsin Myeongjo/);
  assert.match(app, /Times LT Std/);
  assert.match(app, /Jibaek/);
  assert.doesNotMatch(app, /Jibaek 120g/);
  assert.doesNotMatch(app, /Jibaek 260g/);
  assert.doesNotMatch(app, /Jibaek 400g/);
  assert.match(app, /fallbackEditorRange\(contentRoot\)/);
  assert.match(app, /selection\.removeAllRanges\(\)/);
  assert.match(app, /toggleInlineSelection/);
  assert.match(app, /unwrapInlineElement/);
  assert.match(app, /preserveSelectionAroundInlineRemoval/);
  assert.match(app, /restoreSelectionBetweenMarkers/);
  assert.doesNotMatch(app, /lastEditorRange = null;\s*statusRoot\.textContent = `\$\{label\} removed/);
  assert.match(app, /range\.extractContents\(\)/);
  assert.match(app, /document\.createElement\('strong'\)/);
  assert.match(app, /document\.createElement\('u'\)/);
  assert.match(app, /document\.createElement\('em'\)/);
  assert.doesNotMatch(app, /execCommand\('underline'\)/);
  assert.doesNotMatch(app, /execCommand\('bold'\)/);
  assert.doesNotMatch(app, /execCommand\('italic'\)/);
  assert.match(app, /textDecoration/);
  assert.match(app, /fontWeight/);
  assert.match(app, /fontStyle/);
  assert.match(app, /tool-icon--underline/);
  assert.match(app, /tool-icon--bold/);
  assert.match(app, /tool-icon--italic/);
  assert.match(app, /tool-icon--link/);
  assert.match(app, /editor__inline-tools/);
  assert.match(app, /data-action="link"/);
  assert.match(app, /data-action="note-delete"/);
  assert.match(app, /selectedNoteDot/);
  assert.match(app, /deleteSelectedNoteDot/);
  assert.match(app, /footnote deleted\. save to publish/);
  assert.match(app, /data-action="note-image-upload"/);
  assert.match(app, /name="noteImageUpload"/);
  assert.match(app, /type="file"/);
  assert.match(app, /accept="image\/\*"/);
  assert.match(app, /insertHyperlinkNote/);
  assert.match(app, /uploadHyperlinkNoteImage/);
  assert.match(app, /note image uploaded/);
  assert.match(app, /NOTE_IMAGE_WIDTH/);
  assert.match(app, /hyperlinkNoteElement/);
  assert.match(app, /hyperlink note added/);
  assert.match(app, /normalizePromptedLinkUrl/);
  assert.match(app, /sanitizeImageUrl/);
  assert.match(app, /data-image/);
  assert.match(app, /note-popover/);
  assert.match(app, /hyperlinkNoteText/);
  assert.match(app, /noteDotMarkup\(hyperlinkNoteText\(href, noteText, image\), href, image\)/);
  assert.doesNotMatch(app, /각주에 넣을 이미지 주소/);
  assert.match(app, /let lastEditorRange/);
  assert.match(app, /rememberEditorSelection/);
  assert.match(app, /attachEditorSelectionMemory/);
  assert.match(app, /event\.preventDefault\(\)/);
  assert.doesNotMatch(app, /execCommand\('createLink'/);
  assert.doesNotMatch(app, /data-action="note"/);
  assert.match(app, /beforeSelection:\s*true/);
  assert.match(app, /range\.collapse\(false\)/);
  assert.match(app, /note-dot/);
  assert.match(app, /data-note/);
  assert.match(app, /data-url/);
  assert.doesNotMatch(app, /title="\$\{escapeHtml\(url \|\| note \|\| '각주'\)\}"/);
  assert.match(app, /lineHeight/);
  assert.doesNotMatch(app, /data-action="apply-line"/);
  assert.doesNotMatch(app, /selectedParagraphs/);
  assert.match(app, /reader-chrome/);
  assert.match(app, /attachReaderChromeDissolve/);
  assert.doesNotMatch(app, /setTimeout\(hide/);
  assert.match(app, /nextY > 24[\s\S]*hide\(\)/);
  assert.match(app, /topButton\?\.classList\.add\('is-visible'\)/);
  assert.match(app, /topButton\?\.classList\.remove\('is-visible'\)/);
  assert.match(app, /data-line-height/);
  assert.match(app, /sanitizeInlineHtml/);
  assert.match(app, /node\.tagName === 'STRONG' \|\| node\.tagName === 'B'/);
  assert.match(app, /node\.tagName === 'EM' \|\| node\.tagName === 'I'/);
  assert.match(app, /block\.html/);
  assert.match(app, /window\.prompt/);
  assert.match(css, /word-break:\s*keep-all/);
  assert.match(css, /overflow-wrap:\s*anywhere/);
  assert.match(css, /\.reader-index[\s\S]*position:\s*fixed/);
  assert.match(css, /\.reader-layout[\s\S]*display:\s*block/);
  assert.match(css, /\.to-top-button/);
  assert.match(css, /\.to-top-button[\s\S]*border:\s*0/);
  assert.match(css, /\.to-top-button[\s\S]*opacity:\s*0/);
  assert.match(css, /\.to-top-button[\s\S]*right:\s*20px/);
  assert.match(css, /\.to-top-button[\s\S]*bottom:\s*20px/);
  assert.match(css, /\.to-top-button[\s\S]*font-size:\s*0\.58rem/);
  assert.match(css, /\.to-top-button\.is-visible[\s\S]*opacity:\s*0\.34/);
  assert.match(css, /position:\s*fixed/);
  assert.match(css, /@media \(max-width:\s*720px\)/);
  assert.match(css, /\.top-controls/);
  assert.match(css, /transition:\s*opacity 140ms ease/);
  assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.top-controls[\s\S]*position:\s*static/);
  assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.reader-index[\s\S]*position:\s*static/);
  assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.reader-layout[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto/);
  assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.reader-article[\s\S]*grid-column:\s*1 \/ -1/);
  assert.match(css, /\.button-link/);
  assert.doesNotMatch(css, /\.editor__tools/);
  assert.match(css, /\.editor__inline-tools/);
  assert.match(css, /\.text-tool/);
  assert.match(css, /\.editor__settings[\s\S]*border-top:\s*0/);
  assert.match(css, /\.editor__inline-tools[\s\S]*padding-top:\s*0/);
  assert.match(css, /--editor-label-width:\s*92px/);
  assert.match(css, /\.editor__settings label[\s\S]*grid-template-columns:\s*var\(--editor-label-width\) minmax\(0,\s*1fr\)/);
  assert.match(css, /\.editor__style-actions[\s\S]*display:\s*flex/);
  assert.match(css, /\.editor__style-actions[\s\S]*padding-left:\s*calc\(var\(--editor-label-width\) \+ 8px\)/);
  assert.match(css, /\.text-tool[\s\S]*font-size:\s*inherit/);
  assert.match(css, /\.note-dot/);
  assert.match(css, /counter-reset:\s*note-number/);
  assert.match(css, /color:\s*#d11c24/);
  assert.match(css, /:root\[data-theme="dark"\][\s\S]*--note-color:\s*#7aa7ff/);
  assert.match(css, /:root:not\(\[data-theme\]\)[\s\S]*--note-color:\s*#7aa7ff/);
  assert.match(css, /\.note-dot[\s\S]*color:\s*var\(--note-color\)/);
  assert.match(css, /counter-increment:\s*note-number/);
  assert.match(css, /content:\s*counter\(note-number\)/);
  assert.match(css, /font-size:\s*0\.58em/);
  assert.match(css, /\.note-dot:hover,[\s\S]*outline:\s*0/);
  assert.match(css, /\.note-dot\.is-open::after/);
  assert.match(css, /\.note-dot\.is-open::after[\s\S]*font-size:\s*11px/);
  assert.match(app, /if \(!image\) return/);
  assert.match(app, /<img src="\$\{escapeHtml\(image\)\}" alt="">[\s\S]*\$\{dot\.dataset\.note/);
  assert.match(app, /window\.scrollX/);
  assert.match(app, /window\.scrollY/);
  assert.match(css, /--note-image-width/);
  assert.match(css, /\.note-dot\[data-image\]\.is-open::after[\s\S]*display:\s*none/);
  assert.match(css, /\.note-popover\s*\{[^}]*position:\s*absolute/);
  assert.doesNotMatch(css, /\.note-popover\s*\{[^}]*position:\s*fixed/);
  assert.doesNotMatch(css, /\.note-popover::before/);
  assert.doesNotMatch(css, /\.note-popover__close/);
  assert.doesNotMatch(css, /border-radius:\s*10px/);
  assert.match(css, /height:\s*100%/);
  assert.match(css, /text-decoration-style:\s*solid/);
  assert.match(css, /\.index-page[\s\S]*justify-content:\s*center/);
  assert.match(css, /\.index-page__row[\s\S]*justify-content:\s*space-between/);
  assert.match(css, /\.index-page__row[\s\S]*text-decoration:\s*none/);
  assert.match(css, /\.index-page__row:hover,[\s\S]*color:\s*var\(--accent\)/);
});

test('database schema enables RLS and public readers only see published posts', async () => {
  const schema = await file('supabase/schema.sql');

  assert.match(schema, /create table if not exists public\.posts/i);
  assert.match(schema, /enable row level security/i);
  assert.match(schema, /to anon/i);
  assert.match(schema, /status = 'published'/i);
  assert.match(schema, /auth\.uid\(\)/i);
  assert.match(schema, /set_post_updated_at/i);
  assert.match(schema, /authenticated users can manage posts/i);
  assert.match(schema, /insert into storage\.buckets/i);
  assert.match(schema, /post-images/i);
  assert.match(schema, /post images bucket is visible/i);
  assert.match(schema, /authenticated users can upload post images/i);
  assert.doesNotMatch(schema, /centered-draft/i);
  assert.doesNotMatch(schema, /가안: 가운데에 놓인 글/);
});

test('GitHub push can deploy the static site through Pages actions', async () => {
  const packageJson = await file('package.json');
  const workflow = await file('.github/workflows/deploy.yml');
  const buildScript = await file('scripts/build-pages.mjs');

  assert.match(packageJson, /"build"/);
  assert.match(workflow, /deploy-pages/);
  assert.match(workflow, /branches:\s*\[\s*main\s*\]/);
  assert.match(buildScript, /dist/);
  assert.match(buildScript, /fonts/);
  assert.match(buildScript, /admin\.html/);
});
